#!/bin/bash

set -exuo pipefail

# Get the absolute path to the repository root using git
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

echo "====== black ======="
black $(git ls-files | grep '\.py$')

echo "====== autoflake ======="
autoflake --remove-all-unused-imports --in-place $(git ls-files | grep py$ | grep  -v backend/common/schemas.py | grep -v __init__.py)

echo "====== isort ======="
isort --profile black $(git ls-files | grep '\.py$')

echo "====== pyright ======="
pyright backend/

echo "====== pylint ======="
pylint $(git ls-files | grep '\.py$')

echo "====== prettier ======="
(cd frontend; pnpm exec prettier --write .)

echo "====== eslint ======= "
(cd frontend; npm run lint:fix)

echo "====== terraform ======="
(cd terraform/main; terraform fmt -check -recursive)
(cd terraform/main; terraform validate)
(cd terraform/support; terraform fmt -check -recursive)
(cd terraform/support; terraform validate)
